// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/nilian/online/message/GameMessage.proto
// Protobuf Java Version: 4.28.2

package nilian.online.message;

public interface ClientMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ClientMessageType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.ClientMessageType type = 1;</code>
   * @return The type.
   */
  nilian.online.message.ClientMessageType getType();

  /**
   * <code>.PlayerMessage player_info = 2;</code>
   * @return Whether the playerInfo field is set.
   */
  boolean hasPlayerInfo();
  /**
   * <code>.PlayerMessage player_info = 2;</code>
   * @return The playerInfo.
   */
  nilian.online.message.PlayerMessage getPlayerInfo();
  /**
   * <code>.PlayerMessage player_info = 2;</code>
   */
  nilian.online.message.PlayerMessageOrBuilder getPlayerInfoOrBuilder();

  /**
   * <code>int64 timestamp = 3;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
