// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/nilian/online/message/GameMessage.proto
// Protobuf Java Version: 4.28.2

package nilian.online.message;

/**
 * <pre>
 * Client messages
 * </pre>
 *
 * Protobuf enum {@code ClientMessageType}
 */
public enum ClientMessageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CLIENT_MESSAGE_TYPE_UNSPECIFIED = 0;</code>
   */
  CLIENT_MESSAGE_TYPE_UNSPECIFIED(0),
  /**
   * <code>CLIENT_MESSAGE_TYPE_INTRODUCE = 1;</code>
   */
  CLIENT_MESSAGE_TYPE_INTRODUCE(1),
  /**
   * <code>CLIENT_MESSAGE_TYPE_UPDATE_PLACE = 2;</code>
   */
  CLIENT_MESSAGE_TYPE_UPDATE_PLACE(2),
  /**
   * <code>CLIENT_MESSAGE_TYPE_UPDATE_ACT = 3;</code>
   */
  CLIENT_MESSAGE_TYPE_UPDATE_ACT(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      ClientMessageType.class.getName());
  }
  /**
   * <code>CLIENT_MESSAGE_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int CLIENT_MESSAGE_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>CLIENT_MESSAGE_TYPE_INTRODUCE = 1;</code>
   */
  public static final int CLIENT_MESSAGE_TYPE_INTRODUCE_VALUE = 1;
  /**
   * <code>CLIENT_MESSAGE_TYPE_UPDATE_PLACE = 2;</code>
   */
  public static final int CLIENT_MESSAGE_TYPE_UPDATE_PLACE_VALUE = 2;
  /**
   * <code>CLIENT_MESSAGE_TYPE_UPDATE_ACT = 3;</code>
   */
  public static final int CLIENT_MESSAGE_TYPE_UPDATE_ACT_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ClientMessageType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ClientMessageType forNumber(int value) {
    switch (value) {
      case 0: return CLIENT_MESSAGE_TYPE_UNSPECIFIED;
      case 1: return CLIENT_MESSAGE_TYPE_INTRODUCE;
      case 2: return CLIENT_MESSAGE_TYPE_UPDATE_PLACE;
      case 3: return CLIENT_MESSAGE_TYPE_UPDATE_ACT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ClientMessageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ClientMessageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ClientMessageType>() {
          public ClientMessageType findValueByNumber(int number) {
            return ClientMessageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return nilian.online.message.GameMessage.getDescriptor().getEnumTypes().get(3);
  }

  private static final ClientMessageType[] VALUES = values();

  public static ClientMessageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ClientMessageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ClientMessageType)
}

