// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/nilian/online/message/GameMessage.proto
// Protobuf Java Version: 4.28.2

package nilian.online.message;

public final class GameMessage {
  private GameMessage() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      GameMessage.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GameConfigMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GameConfigMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServerMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClientMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5src/main/java/nilian/online/message/Ga" +
      "meMessage.proto\"\242\001\n\rPlayerMessage\022 \n\004typ" +
      "e\030\001 \001(\0162\022.PlayerMessageType\022\021\n\ttimestamp" +
      "\030\002 \001(\003\022\023\n\013player_hash\030\003 \001(\003\022\t\n\001x\030\004 \001(\005\022\t" +
      "\n\001y\030\005 \001(\005\022\021\n\tsuit_code\030\006 \001(\005\022\014\n\004name\030\007 \001" +
      "(\t\022\020\n\010teamCode\030\010 \001(\005\"_\n\021GameConfigMessag" +
      "e\022\013\n\003map\030\001 \001(\t\022\r\n\005theme\030\002 \001(\t\022\033\n\004mode\030\003 " +
      "\001(\0162\r.GameModeType\022\021\n\ttimestamp\030\004 \001(\003\"z\n" +
      "\rServerMessage\022 \n\004type\030\001 \001(\0162\022.ServerMes" +
      "sageType\022\'\n\013game_config\030\002 \001(\0132\022.GameConf" +
      "igMessage\022\036\n\006player\030\003 \001(\0132\016.PlayerMessag" +
      "e\"i\n\rClientMessage\022 \n\004type\030\001 \001(\0162\022.Clien" +
      "tMessageType\022#\n\013player_info\030\002 \001(\0132\016.Play" +
      "erMessage\022\021\n\ttimestamp\030\003 \001(\003*\230\001\n\021PlayerM" +
      "essageType\022#\n\037PLAYER_MESSAGE_TYPE_UNSPEC" +
      "IFIED\020\000\022\035\n\031PLAYER_MESSAGE_TYPE_SPAWN\020\001\022!" +
      "\n\035PLAYER_MESSAGE_TYPE_DISAPPEAR\020\002\022\034\n\030PLA" +
      "YER_MESSAGE_TYPE_MOVE\020\003*t\n\014GameModeType\022" +
      "\036\n\032GAME_MODE_TYPE_UNSPECIFIED\020\000\022\037\n\033GAME_" +
      "MODE_TYPE_FREE_FOR_ALL\020\001\022#\n\037GAME_MODE_TY" +
      "PE_TEAM_DEATH_MATCH\020\002*\227\001\n\021ServerMessageT" +
      "ype\022#\n\037SERVER_MESSAGE_TYPE_UNSPECIFIED\020\000" +
      "\022\037\n\033SERVER_MESSAGE_TYPE_WELCOME\020\001\022\036\n\032SER" +
      "VER_MESSAGE_TYPE_PLAYER\020\002\022\034\n\030SERVER_MESS" +
      "AGE_TYPE_GAME\020\003*\245\001\n\021ClientMessageType\022#\n" +
      "\037CLIENT_MESSAGE_TYPE_UNSPECIFIED\020\000\022!\n\035CL" +
      "IENT_MESSAGE_TYPE_INTRODUCE\020\001\022$\n CLIENT_" +
      "MESSAGE_TYPE_UPDATE_PLACE\020\002\022\"\n\036CLIENT_ME" +
      "SSAGE_TYPE_UPDATE_ACT\020\003B\031\n\025nilian.online" +
      ".messageP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PlayerMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PlayerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PlayerMessage_descriptor,
        new java.lang.String[] { "Type", "Timestamp", "PlayerHash", "X", "Y", "SuitCode", "Name", "TeamCode", });
    internal_static_GameConfigMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GameConfigMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GameConfigMessage_descriptor,
        new java.lang.String[] { "Map", "Theme", "Mode", "Timestamp", });
    internal_static_ServerMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ServerMessage_descriptor,
        new java.lang.String[] { "Type", "GameConfig", "Player", });
    internal_static_ClientMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ClientMessage_descriptor,
        new java.lang.String[] { "Type", "PlayerInfo", "Timestamp", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
