// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/nilian/online/message/GameMessage.proto
// Protobuf Java Version: 4.28.2

package nilian.online.message;

/**
 * <pre>
 * Game configuration messages and enums
 * </pre>
 *
 * Protobuf enum {@code GameModeType}
 */
public enum GameModeType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>GAME_MODE_TYPE_UNSPECIFIED = 0;</code>
   */
  GAME_MODE_TYPE_UNSPECIFIED(0),
  /**
   * <code>GAME_MODE_TYPE_FREE_FOR_ALL = 1;</code>
   */
  GAME_MODE_TYPE_FREE_FOR_ALL(1),
  /**
   * <code>GAME_MODE_TYPE_TEAM_DEATH_MATCH = 2;</code>
   */
  GAME_MODE_TYPE_TEAM_DEATH_MATCH(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      GameModeType.class.getName());
  }
  /**
   * <code>GAME_MODE_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int GAME_MODE_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>GAME_MODE_TYPE_FREE_FOR_ALL = 1;</code>
   */
  public static final int GAME_MODE_TYPE_FREE_FOR_ALL_VALUE = 1;
  /**
   * <code>GAME_MODE_TYPE_TEAM_DEATH_MATCH = 2;</code>
   */
  public static final int GAME_MODE_TYPE_TEAM_DEATH_MATCH_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static GameModeType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static GameModeType forNumber(int value) {
    switch (value) {
      case 0: return GAME_MODE_TYPE_UNSPECIFIED;
      case 1: return GAME_MODE_TYPE_FREE_FOR_ALL;
      case 2: return GAME_MODE_TYPE_TEAM_DEATH_MATCH;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<GameModeType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      GameModeType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<GameModeType>() {
          public GameModeType findValueByNumber(int number) {
            return GameModeType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return nilian.online.message.GameMessage.getDescriptor().getEnumTypes().get(1);
  }

  private static final GameModeType[] VALUES = values();

  public static GameModeType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private GameModeType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:GameModeType)
}

