// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/nilian/online/message/GameMessage.proto
// Protobuf Java Version: 4.28.2

package nilian.online.message;

/**
 * <pre>
 * Player-related messages and enums
 * </pre>
 *
 * Protobuf enum {@code PlayerMessageType}
 */
public enum PlayerMessageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PLAYER_MESSAGE_TYPE_UNSPECIFIED = 0;</code>
   */
  PLAYER_MESSAGE_TYPE_UNSPECIFIED(0),
  /**
   * <code>PLAYER_MESSAGE_TYPE_SPAWN = 1;</code>
   */
  PLAYER_MESSAGE_TYPE_SPAWN(1),
  /**
   * <code>PLAYER_MESSAGE_TYPE_DISAPPEAR = 2;</code>
   */
  PLAYER_MESSAGE_TYPE_DISAPPEAR(2),
  /**
   * <code>PLAYER_MESSAGE_TYPE_MOVE = 3;</code>
   */
  PLAYER_MESSAGE_TYPE_MOVE(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      PlayerMessageType.class.getName());
  }
  /**
   * <code>PLAYER_MESSAGE_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int PLAYER_MESSAGE_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>PLAYER_MESSAGE_TYPE_SPAWN = 1;</code>
   */
  public static final int PLAYER_MESSAGE_TYPE_SPAWN_VALUE = 1;
  /**
   * <code>PLAYER_MESSAGE_TYPE_DISAPPEAR = 2;</code>
   */
  public static final int PLAYER_MESSAGE_TYPE_DISAPPEAR_VALUE = 2;
  /**
   * <code>PLAYER_MESSAGE_TYPE_MOVE = 3;</code>
   */
  public static final int PLAYER_MESSAGE_TYPE_MOVE_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PlayerMessageType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PlayerMessageType forNumber(int value) {
    switch (value) {
      case 0: return PLAYER_MESSAGE_TYPE_UNSPECIFIED;
      case 1: return PLAYER_MESSAGE_TYPE_SPAWN;
      case 2: return PLAYER_MESSAGE_TYPE_DISAPPEAR;
      case 3: return PLAYER_MESSAGE_TYPE_MOVE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PlayerMessageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PlayerMessageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PlayerMessageType>() {
          public PlayerMessageType findValueByNumber(int number) {
            return PlayerMessageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return nilian.online.message.GameMessage.getDescriptor().getEnumTypes().get(0);
  }

  private static final PlayerMessageType[] VALUES = values();

  public static PlayerMessageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PlayerMessageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:PlayerMessageType)
}

