// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/nilian/online/message/GameMessage.proto
// Protobuf Java Version: 4.28.2

package nilian.online.message;

/**
 * Protobuf type {@code PlayerMessage}
 */
public final class PlayerMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PlayerMessage)
    PlayerMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      PlayerMessage.class.getName());
  }
  // Use PlayerMessage.newBuilder() to construct.
  private PlayerMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PlayerMessage() {
    type_ = 0;
    name_ = "";
    nameColor_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return nilian.online.message.GameMessage.internal_static_PlayerMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return nilian.online.message.GameMessage.internal_static_PlayerMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            nilian.online.message.PlayerMessage.class, nilian.online.message.PlayerMessage.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_ = 0;
  /**
   * <code>.PlayerMessageType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.PlayerMessageType type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public nilian.online.message.PlayerMessageType getType() {
    nilian.online.message.PlayerMessageType result = nilian.online.message.PlayerMessageType.forNumber(type_);
    return result == null ? nilian.online.message.PlayerMessageType.UNRECOGNIZED : result;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private long timestamp_ = 0L;
  /**
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int PLAYER_HASH_FIELD_NUMBER = 3;
  private long playerHash_ = 0L;
  /**
   * <code>int64 player_hash = 3;</code>
   * @return The playerHash.
   */
  @java.lang.Override
  public long getPlayerHash() {
    return playerHash_;
  }

  public static final int X_FIELD_NUMBER = 4;
  private int x_ = 0;
  /**
   * <code>int32 x = 4;</code>
   * @return The x.
   */
  @java.lang.Override
  public int getX() {
    return x_;
  }

  public static final int Y_FIELD_NUMBER = 5;
  private int y_ = 0;
  /**
   * <code>int32 y = 5;</code>
   * @return The y.
   */
  @java.lang.Override
  public int getY() {
    return y_;
  }

  public static final int SUIT_CODE_FIELD_NUMBER = 6;
  private int suitCode_ = 0;
  /**
   * <code>int32 suit_code = 6;</code>
   * @return The suitCode.
   */
  @java.lang.Override
  public int getSuitCode() {
    return suitCode_;
  }

  public static final int NAME_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 7;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 7;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAMECOLOR_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nameColor_ = "";
  /**
   * <code>string nameColor = 8;</code>
   * @return The nameColor.
   */
  @java.lang.Override
  public java.lang.String getNameColor() {
    java.lang.Object ref = nameColor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nameColor_ = s;
      return s;
    }
  }
  /**
   * <code>string nameColor = 8;</code>
   * @return The bytes for nameColor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameColorBytes() {
    java.lang.Object ref = nameColor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nameColor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEAMCODE_FIELD_NUMBER = 9;
  private int teamCode_ = 0;
  /**
   * <code>int32 teamCode = 9;</code>
   * @return The teamCode.
   */
  @java.lang.Override
  public int getTeamCode() {
    return teamCode_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != nilian.online.message.PlayerMessageType.PLAYER_MESSAGE_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(2, timestamp_);
    }
    if (playerHash_ != 0L) {
      output.writeInt64(3, playerHash_);
    }
    if (x_ != 0) {
      output.writeInt32(4, x_);
    }
    if (y_ != 0) {
      output.writeInt32(5, y_);
    }
    if (suitCode_ != 0) {
      output.writeInt32(6, suitCode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nameColor_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, nameColor_);
    }
    if (teamCode_ != 0) {
      output.writeInt32(9, teamCode_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != nilian.online.message.PlayerMessageType.PLAYER_MESSAGE_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, timestamp_);
    }
    if (playerHash_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, playerHash_);
    }
    if (x_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, x_);
    }
    if (y_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, y_);
    }
    if (suitCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, suitCode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nameColor_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, nameColor_);
    }
    if (teamCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, teamCode_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof nilian.online.message.PlayerMessage)) {
      return super.equals(obj);
    }
    nilian.online.message.PlayerMessage other = (nilian.online.message.PlayerMessage) obj;

    if (type_ != other.type_) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (getPlayerHash()
        != other.getPlayerHash()) return false;
    if (getX()
        != other.getX()) return false;
    if (getY()
        != other.getY()) return false;
    if (getSuitCode()
        != other.getSuitCode()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getNameColor()
        .equals(other.getNameColor())) return false;
    if (getTeamCode()
        != other.getTeamCode()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + PLAYER_HASH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPlayerHash());
    hash = (37 * hash) + X_FIELD_NUMBER;
    hash = (53 * hash) + getX();
    hash = (37 * hash) + Y_FIELD_NUMBER;
    hash = (53 * hash) + getY();
    hash = (37 * hash) + SUIT_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getSuitCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + NAMECOLOR_FIELD_NUMBER;
    hash = (53 * hash) + getNameColor().hashCode();
    hash = (37 * hash) + TEAMCODE_FIELD_NUMBER;
    hash = (53 * hash) + getTeamCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static nilian.online.message.PlayerMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static nilian.online.message.PlayerMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static nilian.online.message.PlayerMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static nilian.online.message.PlayerMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static nilian.online.message.PlayerMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static nilian.online.message.PlayerMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static nilian.online.message.PlayerMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static nilian.online.message.PlayerMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static nilian.online.message.PlayerMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static nilian.online.message.PlayerMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static nilian.online.message.PlayerMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static nilian.online.message.PlayerMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(nilian.online.message.PlayerMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PlayerMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PlayerMessage)
      nilian.online.message.PlayerMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nilian.online.message.GameMessage.internal_static_PlayerMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nilian.online.message.GameMessage.internal_static_PlayerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nilian.online.message.PlayerMessage.class, nilian.online.message.PlayerMessage.Builder.class);
    }

    // Construct using nilian.online.message.PlayerMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 0;
      timestamp_ = 0L;
      playerHash_ = 0L;
      x_ = 0;
      y_ = 0;
      suitCode_ = 0;
      name_ = "";
      nameColor_ = "";
      teamCode_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return nilian.online.message.GameMessage.internal_static_PlayerMessage_descriptor;
    }

    @java.lang.Override
    public nilian.online.message.PlayerMessage getDefaultInstanceForType() {
      return nilian.online.message.PlayerMessage.getDefaultInstance();
    }

    @java.lang.Override
    public nilian.online.message.PlayerMessage build() {
      nilian.online.message.PlayerMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public nilian.online.message.PlayerMessage buildPartial() {
      nilian.online.message.PlayerMessage result = new nilian.online.message.PlayerMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(nilian.online.message.PlayerMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.playerHash_ = playerHash_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.x_ = x_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.y_ = y_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.suitCode_ = suitCode_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.nameColor_ = nameColor_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.teamCode_ = teamCode_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof nilian.online.message.PlayerMessage) {
        return mergeFrom((nilian.online.message.PlayerMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(nilian.online.message.PlayerMessage other) {
      if (other == nilian.online.message.PlayerMessage.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.getPlayerHash() != 0L) {
        setPlayerHash(other.getPlayerHash());
      }
      if (other.getX() != 0) {
        setX(other.getX());
      }
      if (other.getY() != 0) {
        setY(other.getY());
      }
      if (other.getSuitCode() != 0) {
        setSuitCode(other.getSuitCode());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getNameColor().isEmpty()) {
        nameColor_ = other.nameColor_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (other.getTeamCode() != 0) {
        setTeamCode(other.getTeamCode());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              playerHash_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              x_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              y_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              suitCode_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              nameColor_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 72: {
              teamCode_ = input.readInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>.PlayerMessageType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.PlayerMessageType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.PlayerMessageType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public nilian.online.message.PlayerMessageType getType() {
      nilian.online.message.PlayerMessageType result = nilian.online.message.PlayerMessageType.forNumber(type_);
      return result == null ? nilian.online.message.PlayerMessageType.UNRECOGNIZED : result;
    }
    /**
     * <code>.PlayerMessageType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(nilian.online.message.PlayerMessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.PlayerMessageType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 2;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private long playerHash_ ;
    /**
     * <code>int64 player_hash = 3;</code>
     * @return The playerHash.
     */
    @java.lang.Override
    public long getPlayerHash() {
      return playerHash_;
    }
    /**
     * <code>int64 player_hash = 3;</code>
     * @param value The playerHash to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerHash(long value) {

      playerHash_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 player_hash = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayerHash() {
      bitField0_ = (bitField0_ & ~0x00000004);
      playerHash_ = 0L;
      onChanged();
      return this;
    }

    private int x_ ;
    /**
     * <code>int32 x = 4;</code>
     * @return The x.
     */
    @java.lang.Override
    public int getX() {
      return x_;
    }
    /**
     * <code>int32 x = 4;</code>
     * @param value The x to set.
     * @return This builder for chaining.
     */
    public Builder setX(int value) {

      x_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 x = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearX() {
      bitField0_ = (bitField0_ & ~0x00000008);
      x_ = 0;
      onChanged();
      return this;
    }

    private int y_ ;
    /**
     * <code>int32 y = 5;</code>
     * @return The y.
     */
    @java.lang.Override
    public int getY() {
      return y_;
    }
    /**
     * <code>int32 y = 5;</code>
     * @param value The y to set.
     * @return This builder for chaining.
     */
    public Builder setY(int value) {

      y_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 y = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearY() {
      bitField0_ = (bitField0_ & ~0x00000010);
      y_ = 0;
      onChanged();
      return this;
    }

    private int suitCode_ ;
    /**
     * <code>int32 suit_code = 6;</code>
     * @return The suitCode.
     */
    @java.lang.Override
    public int getSuitCode() {
      return suitCode_;
    }
    /**
     * <code>int32 suit_code = 6;</code>
     * @param value The suitCode to set.
     * @return This builder for chaining.
     */
    public Builder setSuitCode(int value) {

      suitCode_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 suit_code = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuitCode() {
      bitField0_ = (bitField0_ & ~0x00000020);
      suitCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 7;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 7;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 7;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 7;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object nameColor_ = "";
    /**
     * <code>string nameColor = 8;</code>
     * @return The nameColor.
     */
    public java.lang.String getNameColor() {
      java.lang.Object ref = nameColor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nameColor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nameColor = 8;</code>
     * @return The bytes for nameColor.
     */
    public com.google.protobuf.ByteString
        getNameColorBytes() {
      java.lang.Object ref = nameColor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nameColor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nameColor = 8;</code>
     * @param value The nameColor to set.
     * @return This builder for chaining.
     */
    public Builder setNameColor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nameColor_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string nameColor = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearNameColor() {
      nameColor_ = getDefaultInstance().getNameColor();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string nameColor = 8;</code>
     * @param value The bytes for nameColor to set.
     * @return This builder for chaining.
     */
    public Builder setNameColorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nameColor_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private int teamCode_ ;
    /**
     * <code>int32 teamCode = 9;</code>
     * @return The teamCode.
     */
    @java.lang.Override
    public int getTeamCode() {
      return teamCode_;
    }
    /**
     * <code>int32 teamCode = 9;</code>
     * @param value The teamCode to set.
     * @return This builder for chaining.
     */
    public Builder setTeamCode(int value) {

      teamCode_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int32 teamCode = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTeamCode() {
      bitField0_ = (bitField0_ & ~0x00000100);
      teamCode_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PlayerMessage)
  }

  // @@protoc_insertion_point(class_scope:PlayerMessage)
  private static final nilian.online.message.PlayerMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new nilian.online.message.PlayerMessage();
  }

  public static nilian.online.message.PlayerMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PlayerMessage>
      PARSER = new com.google.protobuf.AbstractParser<PlayerMessage>() {
    @java.lang.Override
    public PlayerMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PlayerMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PlayerMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public nilian.online.message.PlayerMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

