// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/nilian/online/message/GameMessage.proto
// Protobuf Java Version: 4.28.2

package nilian.online.message;

public interface ServerMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServerMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ServerMessageType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.ServerMessageType type = 1;</code>
   * @return The type.
   */
  nilian.online.message.ServerMessageType getType();

  /**
   * <code>.GameConfigMessage game_config = 2;</code>
   * @return Whether the gameConfig field is set.
   */
  boolean hasGameConfig();
  /**
   * <code>.GameConfigMessage game_config = 2;</code>
   * @return The gameConfig.
   */
  nilian.online.message.GameConfigMessage getGameConfig();
  /**
   * <code>.GameConfigMessage game_config = 2;</code>
   */
  nilian.online.message.GameConfigMessageOrBuilder getGameConfigOrBuilder();

  /**
   * <code>.PlayerMessage player = 3;</code>
   * @return Whether the player field is set.
   */
  boolean hasPlayer();
  /**
   * <code>.PlayerMessage player = 3;</code>
   * @return The player.
   */
  nilian.online.message.PlayerMessage getPlayer();
  /**
   * <code>.PlayerMessage player = 3;</code>
   */
  nilian.online.message.PlayerMessageOrBuilder getPlayerOrBuilder();
}
