// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/nilian/online/message/GameMessage.proto
// Protobuf Java Version: 4.28.2

package nilian.online.message;

/**
 * Protobuf type {@code ServerMessage}
 */
public final class ServerMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ServerMessage)
    ServerMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      ServerMessage.class.getName());
  }
  // Use ServerMessage.newBuilder() to construct.
  private ServerMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ServerMessage() {
    type_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return nilian.online.message.GameMessage.internal_static_ServerMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return nilian.online.message.GameMessage.internal_static_ServerMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            nilian.online.message.ServerMessage.class, nilian.online.message.ServerMessage.Builder.class);
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_ = 0;
  /**
   * <code>.ServerMessageType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.ServerMessageType type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public nilian.online.message.ServerMessageType getType() {
    nilian.online.message.ServerMessageType result = nilian.online.message.ServerMessageType.forNumber(type_);
    return result == null ? nilian.online.message.ServerMessageType.UNRECOGNIZED : result;
  }

  public static final int GAME_CONFIG_FIELD_NUMBER = 2;
  private nilian.online.message.GameConfigMessage gameConfig_;
  /**
   * <code>.GameConfigMessage game_config = 2;</code>
   * @return Whether the gameConfig field is set.
   */
  @java.lang.Override
  public boolean hasGameConfig() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.GameConfigMessage game_config = 2;</code>
   * @return The gameConfig.
   */
  @java.lang.Override
  public nilian.online.message.GameConfigMessage getGameConfig() {
    return gameConfig_ == null ? nilian.online.message.GameConfigMessage.getDefaultInstance() : gameConfig_;
  }
  /**
   * <code>.GameConfigMessage game_config = 2;</code>
   */
  @java.lang.Override
  public nilian.online.message.GameConfigMessageOrBuilder getGameConfigOrBuilder() {
    return gameConfig_ == null ? nilian.online.message.GameConfigMessage.getDefaultInstance() : gameConfig_;
  }

  public static final int PLAYER_FIELD_NUMBER = 3;
  private nilian.online.message.PlayerMessage player_;
  /**
   * <code>.PlayerMessage player = 3;</code>
   * @return Whether the player field is set.
   */
  @java.lang.Override
  public boolean hasPlayer() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.PlayerMessage player = 3;</code>
   * @return The player.
   */
  @java.lang.Override
  public nilian.online.message.PlayerMessage getPlayer() {
    return player_ == null ? nilian.online.message.PlayerMessage.getDefaultInstance() : player_;
  }
  /**
   * <code>.PlayerMessage player = 3;</code>
   */
  @java.lang.Override
  public nilian.online.message.PlayerMessageOrBuilder getPlayerOrBuilder() {
    return player_ == null ? nilian.online.message.PlayerMessage.getDefaultInstance() : player_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != nilian.online.message.ServerMessageType.SERVER_MESSAGE_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getGameConfig());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getPlayer());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != nilian.online.message.ServerMessageType.SERVER_MESSAGE_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getGameConfig());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPlayer());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof nilian.online.message.ServerMessage)) {
      return super.equals(obj);
    }
    nilian.online.message.ServerMessage other = (nilian.online.message.ServerMessage) obj;

    if (type_ != other.type_) return false;
    if (hasGameConfig() != other.hasGameConfig()) return false;
    if (hasGameConfig()) {
      if (!getGameConfig()
          .equals(other.getGameConfig())) return false;
    }
    if (hasPlayer() != other.hasPlayer()) return false;
    if (hasPlayer()) {
      if (!getPlayer()
          .equals(other.getPlayer())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    if (hasGameConfig()) {
      hash = (37 * hash) + GAME_CONFIG_FIELD_NUMBER;
      hash = (53 * hash) + getGameConfig().hashCode();
    }
    if (hasPlayer()) {
      hash = (37 * hash) + PLAYER_FIELD_NUMBER;
      hash = (53 * hash) + getPlayer().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static nilian.online.message.ServerMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static nilian.online.message.ServerMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static nilian.online.message.ServerMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static nilian.online.message.ServerMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static nilian.online.message.ServerMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static nilian.online.message.ServerMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static nilian.online.message.ServerMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static nilian.online.message.ServerMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static nilian.online.message.ServerMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static nilian.online.message.ServerMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static nilian.online.message.ServerMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static nilian.online.message.ServerMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(nilian.online.message.ServerMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ServerMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ServerMessage)
      nilian.online.message.ServerMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nilian.online.message.GameMessage.internal_static_ServerMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nilian.online.message.GameMessage.internal_static_ServerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nilian.online.message.ServerMessage.class, nilian.online.message.ServerMessage.Builder.class);
    }

    // Construct using nilian.online.message.ServerMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getGameConfigFieldBuilder();
        getPlayerFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 0;
      gameConfig_ = null;
      if (gameConfigBuilder_ != null) {
        gameConfigBuilder_.dispose();
        gameConfigBuilder_ = null;
      }
      player_ = null;
      if (playerBuilder_ != null) {
        playerBuilder_.dispose();
        playerBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return nilian.online.message.GameMessage.internal_static_ServerMessage_descriptor;
    }

    @java.lang.Override
    public nilian.online.message.ServerMessage getDefaultInstanceForType() {
      return nilian.online.message.ServerMessage.getDefaultInstance();
    }

    @java.lang.Override
    public nilian.online.message.ServerMessage build() {
      nilian.online.message.ServerMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public nilian.online.message.ServerMessage buildPartial() {
      nilian.online.message.ServerMessage result = new nilian.online.message.ServerMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(nilian.online.message.ServerMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.gameConfig_ = gameConfigBuilder_ == null
            ? gameConfig_
            : gameConfigBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.player_ = playerBuilder_ == null
            ? player_
            : playerBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof nilian.online.message.ServerMessage) {
        return mergeFrom((nilian.online.message.ServerMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(nilian.online.message.ServerMessage other) {
      if (other == nilian.online.message.ServerMessage.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.hasGameConfig()) {
        mergeGameConfig(other.getGameConfig());
      }
      if (other.hasPlayer()) {
        mergePlayer(other.getPlayer());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getGameConfigFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getPlayerFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>.ServerMessageType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.ServerMessageType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.ServerMessageType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public nilian.online.message.ServerMessageType getType() {
      nilian.online.message.ServerMessageType result = nilian.online.message.ServerMessageType.forNumber(type_);
      return result == null ? nilian.online.message.ServerMessageType.UNRECOGNIZED : result;
    }
    /**
     * <code>.ServerMessageType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(nilian.online.message.ServerMessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ServerMessageType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private nilian.online.message.GameConfigMessage gameConfig_;
    private com.google.protobuf.SingleFieldBuilder<
        nilian.online.message.GameConfigMessage, nilian.online.message.GameConfigMessage.Builder, nilian.online.message.GameConfigMessageOrBuilder> gameConfigBuilder_;
    /**
     * <code>.GameConfigMessage game_config = 2;</code>
     * @return Whether the gameConfig field is set.
     */
    public boolean hasGameConfig() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.GameConfigMessage game_config = 2;</code>
     * @return The gameConfig.
     */
    public nilian.online.message.GameConfigMessage getGameConfig() {
      if (gameConfigBuilder_ == null) {
        return gameConfig_ == null ? nilian.online.message.GameConfigMessage.getDefaultInstance() : gameConfig_;
      } else {
        return gameConfigBuilder_.getMessage();
      }
    }
    /**
     * <code>.GameConfigMessage game_config = 2;</code>
     */
    public Builder setGameConfig(nilian.online.message.GameConfigMessage value) {
      if (gameConfigBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        gameConfig_ = value;
      } else {
        gameConfigBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.GameConfigMessage game_config = 2;</code>
     */
    public Builder setGameConfig(
        nilian.online.message.GameConfigMessage.Builder builderForValue) {
      if (gameConfigBuilder_ == null) {
        gameConfig_ = builderForValue.build();
      } else {
        gameConfigBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.GameConfigMessage game_config = 2;</code>
     */
    public Builder mergeGameConfig(nilian.online.message.GameConfigMessage value) {
      if (gameConfigBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          gameConfig_ != null &&
          gameConfig_ != nilian.online.message.GameConfigMessage.getDefaultInstance()) {
          getGameConfigBuilder().mergeFrom(value);
        } else {
          gameConfig_ = value;
        }
      } else {
        gameConfigBuilder_.mergeFrom(value);
      }
      if (gameConfig_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.GameConfigMessage game_config = 2;</code>
     */
    public Builder clearGameConfig() {
      bitField0_ = (bitField0_ & ~0x00000002);
      gameConfig_ = null;
      if (gameConfigBuilder_ != null) {
        gameConfigBuilder_.dispose();
        gameConfigBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.GameConfigMessage game_config = 2;</code>
     */
    public nilian.online.message.GameConfigMessage.Builder getGameConfigBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getGameConfigFieldBuilder().getBuilder();
    }
    /**
     * <code>.GameConfigMessage game_config = 2;</code>
     */
    public nilian.online.message.GameConfigMessageOrBuilder getGameConfigOrBuilder() {
      if (gameConfigBuilder_ != null) {
        return gameConfigBuilder_.getMessageOrBuilder();
      } else {
        return gameConfig_ == null ?
            nilian.online.message.GameConfigMessage.getDefaultInstance() : gameConfig_;
      }
    }
    /**
     * <code>.GameConfigMessage game_config = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        nilian.online.message.GameConfigMessage, nilian.online.message.GameConfigMessage.Builder, nilian.online.message.GameConfigMessageOrBuilder> 
        getGameConfigFieldBuilder() {
      if (gameConfigBuilder_ == null) {
        gameConfigBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            nilian.online.message.GameConfigMessage, nilian.online.message.GameConfigMessage.Builder, nilian.online.message.GameConfigMessageOrBuilder>(
                getGameConfig(),
                getParentForChildren(),
                isClean());
        gameConfig_ = null;
      }
      return gameConfigBuilder_;
    }

    private nilian.online.message.PlayerMessage player_;
    private com.google.protobuf.SingleFieldBuilder<
        nilian.online.message.PlayerMessage, nilian.online.message.PlayerMessage.Builder, nilian.online.message.PlayerMessageOrBuilder> playerBuilder_;
    /**
     * <code>.PlayerMessage player = 3;</code>
     * @return Whether the player field is set.
     */
    public boolean hasPlayer() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.PlayerMessage player = 3;</code>
     * @return The player.
     */
    public nilian.online.message.PlayerMessage getPlayer() {
      if (playerBuilder_ == null) {
        return player_ == null ? nilian.online.message.PlayerMessage.getDefaultInstance() : player_;
      } else {
        return playerBuilder_.getMessage();
      }
    }
    /**
     * <code>.PlayerMessage player = 3;</code>
     */
    public Builder setPlayer(nilian.online.message.PlayerMessage value) {
      if (playerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        player_ = value;
      } else {
        playerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.PlayerMessage player = 3;</code>
     */
    public Builder setPlayer(
        nilian.online.message.PlayerMessage.Builder builderForValue) {
      if (playerBuilder_ == null) {
        player_ = builderForValue.build();
      } else {
        playerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.PlayerMessage player = 3;</code>
     */
    public Builder mergePlayer(nilian.online.message.PlayerMessage value) {
      if (playerBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          player_ != null &&
          player_ != nilian.online.message.PlayerMessage.getDefaultInstance()) {
          getPlayerBuilder().mergeFrom(value);
        } else {
          player_ = value;
        }
      } else {
        playerBuilder_.mergeFrom(value);
      }
      if (player_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.PlayerMessage player = 3;</code>
     */
    public Builder clearPlayer() {
      bitField0_ = (bitField0_ & ~0x00000004);
      player_ = null;
      if (playerBuilder_ != null) {
        playerBuilder_.dispose();
        playerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.PlayerMessage player = 3;</code>
     */
    public nilian.online.message.PlayerMessage.Builder getPlayerBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getPlayerFieldBuilder().getBuilder();
    }
    /**
     * <code>.PlayerMessage player = 3;</code>
     */
    public nilian.online.message.PlayerMessageOrBuilder getPlayerOrBuilder() {
      if (playerBuilder_ != null) {
        return playerBuilder_.getMessageOrBuilder();
      } else {
        return player_ == null ?
            nilian.online.message.PlayerMessage.getDefaultInstance() : player_;
      }
    }
    /**
     * <code>.PlayerMessage player = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        nilian.online.message.PlayerMessage, nilian.online.message.PlayerMessage.Builder, nilian.online.message.PlayerMessageOrBuilder> 
        getPlayerFieldBuilder() {
      if (playerBuilder_ == null) {
        playerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            nilian.online.message.PlayerMessage, nilian.online.message.PlayerMessage.Builder, nilian.online.message.PlayerMessageOrBuilder>(
                getPlayer(),
                getParentForChildren(),
                isClean());
        player_ = null;
      }
      return playerBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:ServerMessage)
  }

  // @@protoc_insertion_point(class_scope:ServerMessage)
  private static final nilian.online.message.ServerMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new nilian.online.message.ServerMessage();
  }

  public static nilian.online.message.ServerMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerMessage>
      PARSER = new com.google.protobuf.AbstractParser<ServerMessage>() {
    @java.lang.Override
    public ServerMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ServerMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServerMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public nilian.online.message.ServerMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

